---
###- hosts: sslcerts
- hosts: foreman.bustraan.lab
  gather_facts: true
  become: true

  tasks:
    - name: Getting latest Zero-SSL certs from raptor
      shell: |
         cd /home/ansible/playbooks/dyn-ssl/certs
         curl -s https://raptor.bustraan.net/certs/fullchain.cer -O
         curl -s https://raptor.bustraan.net/certs/bustraan.net.cer -O
         curl -s https://raptor.bustraan.net/certs/bustraan.net.key -O
      delegate_to: localhost
      run_once: true

    - name: get the rpm package facts
      package_facts:
        manager: auto

    - block:
        - name: Host has nginx installed
          debug:
            msg: "Nginx found on {{ ansible_hostname }}"

        - name: Copy certificate files to nginx host in proper location and naming convention
          copy:
            src: "{{ item.src_file }}"
            dest: "{{ item.dst_file }}"
            owner: root
            group: root
            mode: '0644'
          with_items:
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: /etc/nginx/bustraan.net.crt
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: /etc/nginx/bustraan.net.key
          notify: restart nginx
      when: ('nginx' in ansible_facts.packages) and (ansible_os_family == 'RedHat')

    - block:
        - name: Host has Apache and not Foreman installed
          debug:
            msg: "Apache found on {{ ansible_hostname }}"

        - name: Copy certificate files to apache host in proper location and naming convention
          copy:
            src: "{{ item.src_file }}"
            dest: "{{ item.dst_file }}"
            owner: root
            group: root
            mode: '0644'
          with_items:
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: /etc/httpd/bustraan.net.crt
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: /etc/httpd/bustraan.net.key
          notify: restart apache
      when: ('httpd' in ansible_facts.packages) and ('foreman' not in ansible_facts.packages) and (ansible_os_family == 'RedHat')

    - block:
        - name: Host has Apache and Foreman installed
          debug:
            msg: "Apache found on {{ ansible_hostname }}"

        - name: Copy certificate files to apache foreman host in proper location and naming convention
          copy:
            src: "{{ item.src_file }}"
            dest: "{{ item.dst_file }}"
            owner: root
            group: root
            mode: '0644'
          with_items:
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: /etc/puppetlabs/puppet/ssl/certs/ca.pem
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: /etc/puppetlabs/puppet/ssl/private_keys/foreman.bustraan.net.pem
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.cer
              dst_file: /etc/puppetlabs/puppet/ssl/certs/foreman.bustraan.net.pem
          notify: restart apache
      when: ('httpd' in ansible_facts.packages) and ('foreman' in ansible_facts.packages) and (ansible_os_family == 'RedHat')

    - block:
        - name: RHEL Cockpit host is found 
          debug:
            msg: "Cockpit found on {{ ansible_hostname }}"

        - name: Copy bustraan certs to /etc/cockpit/ws-certs.d/
          copy:
            src: "{{ item.file1 }}"
            dest: "{{ item.file2 }}"
            owner: root
            group: root
            mode: "{{ item.mode }}"
          with_items:
            - file1: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.cer
              file2: /etc/cockpit/ws-certs.d/bustraan.crt
              mode: '0644'
            - file1: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              file2: /etc/cockpit/ws-certs.d/bustraan.key
              mode: '0644'

        - name: Remove default cockpit certs
          file:
            path: "{{ item.file1 }}"
            state: absent
          with_items:
            - file1: '/etc/cockpit/ws-certs.d/0-self-signed-ca.pem'
            - file1: '/etc/cockpit/ws-certs.d/0-self-signed.cert'
            - file1: '/etc/cockpit/ws-certs.d/0-self-signed.key'
          notify: restart cockpit.socket
      when: ('cockpit' in ansible_facts.packages) and (ansible_os_family == 'RedHat')

    - block:
        - name: Copy certificate files to Proxmox host
          debug:
            msg: "Proxmox found on {{ ansible_hostname }}"

        - name: Copy certificate files to proxmox ve hosts in proper location and naming convention
          copy:
            src: "{{ item.src_file }}"
            dest: "{{ item.dst_file }}"
            owner: root
            group: www-data
            mode: '0640'
          with_items:
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: "/etc/pve/nodes/{{ ansible_nodename }}/pveproxy-ssl.pem"
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: "/etc/pve/nodes/{{ ansible_nodename }}/pveproxy-ssl.key"
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: /etc/pve/local/pveproxy-ssl.pem
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: /etc/pve/local/pveproxy-ssl.key
          notify: restart pveproxy, restart pvedaemon
      when: ('pve-qemu-kvm' in ansible_facts.packages) and (ansible_os_family == 'Debian')

    - block:
        - name: Copy certificate files to GitLab host
          debug:
            msg: "Gitlab found on {{ ansible_hostname }}"

        - name: Copy certificate files to gitlab host in proper location and naming convention
          copy:
            src: "{{ item.src_file }}"
            dest: "{{ item.dst_file }}"
            owner: root
            group: root
            mode: '0640'
          with_items:
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/fullchain.cer
              dst_file: "/etc/gitlab/ssl/gitlab.bustraan.net.crt"
            - src_file: /home/ansible/playbooks/dyn-ssl/certs/bustraan.net.key
              dst_file: "/etc/gitlab/ssl/gitlab.bustraan.net.key"
          notify: restart gitlab-runsvdir
      when: inventory_hostname == 'git.bustraan.lab'

      #/etc/gitlab/ssl/gitlab.bustraan.net.crt;
      #/etc/gitlab/ssl/gitlab.bustraan.net.key;

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart apache
      service: name=httpd state=restarted

    - name: restart cockpit.socket
      service: name=cockpit.socket state=restarted

    - name: restart pveproxy
      service: name=pveproxy state=restarted

    - name: restart pvedaemon
      service: name=pvedeamon state=restarted

    - name: restart gitlab-runsvdir
      service: name=gitlab-runsvdir state=restarted
